language: python

python:
  - "3.6"

install:
  - pip install numpy
  - pip install pandas
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls

script:
  - pytest --cov=qstrader/
  - flake8 --ignore E501 tests

after_success:
  - coveralls