language: python

python:
  - "3.7"

before_install:
  - export PYTHONPATH=$PYTHONPATH:$(pwd) 

install:
  - pip install numpy
  - pip install pandas
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
  - pip install flake8

script:
  - pytest --cov=qstrader/
  - flake8 --ignore E501 tests

after_success:
  - coveralls
